services:
  mysql:
    container_name: mysql-tfs143
    image: mysql:8.0
    restart: always
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: tfs143
      MYSQL_USER: tfs143
      MYSQL_PASSWORD: tfs143
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
      - mysql-data:/var/lib/mysql
    networks:
      - tfs143-net

  server:
    container_name: server-tfs143
    build:
      context: .
    restart: always
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - .:/srv
    networks:
      - tfs143-net
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  tfs143-net:
    driver: bridge
